const COMPONENT_TYPES = require('./COMPONENT_TYPES');

const COMPONENT_CHOICES = [
  COMPONENT_TYPES.SFC,
  COMPONENT_TYPES.CLASS,
  COMPONENT_TYPES.HOC,
  COMPONENT_TYPES.PAGE,
  COMPONENT_TYPES.PURE,
  COMPONENT_TYPES.SCREEN,
];

module.exports = COMPONENT_CHOICES;
