const FUNCTION_TYPES = require('./FUNCTION_TYPES');
const FUNCTION_CHOICES = require('./FUNCTION_CHOICES');
const COMPONENT_TYPES = require('./COMPONENT_TYPES');
const COMPONENT_CHOICES = require('./COMPONENT_CHOICES');

module.exports = {
  FUNCTION_TYPES,
  FUNCTION_CHOICES,
  COMPONENT_TYPES,
  COMPONENT_CHOICES,
};
